spring:
  mail:
    host: ${MAIL_HOST:smtp.yandex.com.tr}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:info@ingress.az}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: false
    protocol: smtp
